### ISSUE TITLE
how do i train

### ISSUE THREAD

**Issue by EXOTIKIAN** [255BITS/HyperGAN#159]
whenever i try to train in hypergan i doesn't work so how do i do it the instructions aren't clear to me 
I am very new to hypergan

**Comment by martyn** [comment]
Hi, sorry for the delay answering you.

Do you mean that the default configurations are diverging during training?  This is probably because hypergan is in beta and hard to stabilize right now.  We are working towards stable configurations.

If hypergan itself is causing errors please copy and paste the error message.

**Comment by EXOTIKIAN** [comment]
im really new to hypergan i just dont completely get everything like training
