### ISSUE TITLE
No module named 'hyperchamber'

### ISSUE THREAD

**Issue by mgarbade** [255BITS/HyperGAN#51]
While trying to run the toy example the program unfortunately crashes immediately with this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/hypergan", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/garbade/CloudStation/libs/dcgan/09_hypergan/hypergan/bin/hypergan", line 5, in <module>
    import hypergan as hg
  File "/usr/local/lib/python3.4/dist-packages/hypergan/__init__.py", line 2, in <module>
    from .gan import GAN
  File "/usr/local/lib/python3.4/dist-packages/hypergan/gan.py", line 4, in <module>
    from hyperchamber import Config
ImportError: No module named 'hyperchamber'
```

I tried to install hyperchamber using  

    pip3 install hyperchamber

But the error persists. Any ideas? 
Is the installation of hyperchamber more evolved?
When I just start python3 from terminal, I can `import hyperchamber` so I'm not sure what is going wrong...

I'm using TF 1.0 - GPU version, python 3.4, Ubuntu 14.04

**Comment by martyn** [comment]
One thing to try is forcing an upgrade/reinstall of hyperchamber(in case an old one is installed)

You can try running

```
pip3 install hyperchamber --upgrade --force-reinstall
```

If that doesn't work, do either of these commands work? 

`python3 -c 'import hypergan'`

`python3 -c 'import hyperchamber'`

**Comment by mgarbade** [comment]
I did all three successfully but the problem persists...

**Comment by mgarbade** [comment]
That is working, thanks :).

Unfortunately the training doesn't seem to converge. While training on my own data (the same that I used for dcgan training) the output samples look unstructured. 

I was using 

    python3 bin/hypergan train ~/path/to/my/images/ -s 64x64x3 -f png -b 64 --config examples/configs/improved-gan.json

Is the size of my images too big maybe? Is it possible too use the same configuration for generator and discriminator as the dcgan paper? Which of the config files would correspond to that?

**Comment by martyn** [comment]
I'm glad it's working for you now.

The default configuration issue is because of #50(bad defaults).  As for stardard DCGAN, at one point it was working.  The place to review the configuration options is `~/.hypergan/config/<config>.json'.

This has a lot of the standard dcgan options, though it's not exactly the same: 
https://github.com/255BITS/HyperGAN/blob/master/examples/configs/improved-gan.json

Here's a good lsgan one(used in samples):
https://github.com/255BITS/HyperGAN/blob/master/examples/configs/rmsprop-lsgan.json
